### PR TITLE
HTML email templating

### PR DESCRIPTION
**Pull request by victoriadrake**
Picking up accidentally closed PR.

@bikerwhocodes I added error feedback to the file parsing line. I'm not sure this works the way you expect: we get `could not get email template: open template.html: no such file or directory`.

### CODE REVIEW

**Comment by bikerwhocodes** [comment]
Ok cool.

**Comment by bikerwhocodes** [comment]
Any updates on this?

**Comment by victoriadrake** [comment]
@bikerwhocodes Are you still interested in taking on this PR? If not, I can open it up for more help!

**Comment by bikerwhocodes** [comment]
Yes I am, I’ll take a look again.

**Comment by bikerwhocodes** [comment]
@victoriadrake found a fix but I can't commit to this PR so might have to make a new one

**Comment by victoriadrake** [comment]
Moved to #4!

**Comment by bikerwhocodes** [comment]
we still need to merge the updated branch :bikerwhocodes-master to master in order to see the changes.

**Pull request closed without merging**
