### PR TITLE
Fix template error

### LINKED ISSUE #1: Better handling for HTML emails
**Is your feature request related to a problem? Please describe.**

HTML markup for rich emails is currently handled with a couple cumbersome strings:

https://github.com/victoriadrake/rss-mailer/blob/249fce933760e3e44d84f7637ad91ef129b4f7c1/main.go#L209-L210

**Describe the solution you'd like**

Email styling and HTML should be easier to edit and maintain.

**Describe alternatives you've considered**

- An external filesystem can be used to house a file that the Lambda function can read from. [Here's one example](https://aws.amazon.com/blogs/aws/new-a-shared-file-system-for-your-lambda-functions/).

- Strings can be stored as environment variables, but the necessary escaping makes HTML even more cumbersome.

### PR DESCRIPTION
**Pull request by bikerwhocodes**
Sorry I missed the "." inform of the template variables

### CODE REVIEW

**Comment by victoriadrake** [comment]
Thank you for the update! I appreciate your effort.

It doesn't appear that the template variables were the issue. I think the fundamental problem is that the template file isn't stored anywhere that Lambda knows about. Running this application in Lambda isn't like running it on your computer; Lambda has no central file storage, which is why we get this error:

```text
could not get email template: open template.html: no such file or directory
```

This is returned from https://github.com/victoriadrake/rss-mailer/blob/4d5eed6de884267fa63d5e40669e04dd81eb3ab3/main.go#L223-L226

To solve this puzzle, we'll need to find a way to store the template file in a place Lambda can access it. Let me know if you'd like me to open up the issue for other help!

**Comment by bikerwhocodes** [comment]
try putting "./template.html" and make sure the html file is along side the go binary

**Comment by victoriadrake** [comment]
I finally figured out what you meant! I added the `template.html` file to the Zip archive that is uploaded as the function code and this seems to work. Thank you for the PR Nihal!

**Comment by bikerwhocodes** [comment]
don't forget to merge bikerwhocodes-master to master. :) 
also do u wanna dockerize this, if yes let me know?

**Pull request merged**
